name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  pages: write


jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare
        run: |
          mkdir -p public
          cp -r mysiar-data-flow public/
          touch public/check.txt

      - name: List publish folder
        run: |
          ls -la public

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'public'

      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: deployment
        uses: actions/deploy-pages@v4